services:
  - type: web
    name: estacionamienti-back
    env: go
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080
